/* Generated using lvgl_img_converter.py (bundle_images_to_c - Default BlackBG/WhiteFG) */
/* Contains 6 image(s). */
#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_ALT_0
#define LV_ATTRIBUTE_IMG_ALT_0
#endif

// Autogenerated map from alt_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_ALT_0 uint8_t alt_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x0f, 0x80, 0x02, 0x40, 0x02, 0x40, 0x0f, 0x80, 0x00, 0x00, 0x0f, 0xc0, 0x08, 0x00,
    0x08, 0x40, 0x00, 0x40, 0x0f, 0xc0, 0x00, 0x40, 0x00, 0x40, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_CMD_0
#define LV_ATTRIBUTE_IMG_CMD_0
#endif

// Autogenerated map from cmd_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_CMD_0 uint8_t cmd_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x18, 0x60, 0x24, 0x90, 0x24, 0x90, 0x1f, 0xe0, 0x04, 0x80, 0x04, 0x80,
    0x1f, 0xe0, 0x24, 0x90, 0x24, 0x90, 0x18, 0x60, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_CONTROL_0
#define LV_ATTRIBUTE_IMG_CONTROL_0
#endif

// Autogenerated map from control_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_CONTROL_0 uint8_t control_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x80, 0x00, 0xc0, 0x00, 0x60, 0x00, 0x30, 0x00, 0x30,
    0x00, 0x60, 0x00, 0xc0, 0x01, 0x80, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_OPT_0
#define LV_ATTRIBUTE_IMG_OPT_0
#endif

// Autogenerated map from opt_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_OPT_0 uint8_t opt_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x00, 0x30, 0x00, 0x30, 0x01, 0xf0, 0x0f, 0xc0, 0x3e, 0x00,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_SHIFT_0
#define LV_ATTRIBUTE_IMG_SHIFT_0
#endif

// Autogenerated map from shift_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_SHIFT_0 uint8_t shift_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x02, 0x00, 0x03, 0x00, 0x03, 0x80, 0x3e, 0xc0, 0x20, 0x60, 0x20, 0x30, 0x20, 0x30,
    0x20, 0x60, 0x3e, 0xc0, 0x03, 0x80, 0x03, 0x00, 0x02, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_WIN_0
#define LV_ATTRIBUTE_IMG_WIN_0
#endif

// Autogenerated map from win_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_WIN_0 uint8_t win_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x1d, 0xc0, 0x1d, 0xc0, 0x1d, 0xe0, 0x00, 0x00, 0x3d, 0xe0, 0x3d, 0xe0,
    0x3d, 0xf0, 0x3d, 0xf0, 0x7d, 0xf0, 0x7d, 0xf0, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_ALT_WHITE_0
#define LV_ATTRIBUTE_IMG_ALT_WHITE_0
#endif

// Autogenerated map from alt_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_ALT_WHITE_0 uint8_t alt_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x0f, 0x80, 0x02, 0x40, 0x02, 0x40, 0x0f, 0x80, 0x00, 0x00, 0x0f, 0xc0, 0x08, 0x00,
    0x08, 0x40, 0x00, 0x40, 0x0f, 0xc0, 0x00, 0x40, 0x00, 0x40, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_CMD_WHITE_0
#define LV_ATTRIBUTE_IMG_CMD_WHITE_0
#endif

// Autogenerated map from cmd_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_CMD_WHITE_0 uint8_t cmd_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x18, 0x60, 0x24, 0x90, 0x24, 0x90, 0x1f, 0xe0, 0x04, 0x80, 0x04, 0x80,
    0x1f, 0xe0, 0x24, 0x90, 0x24, 0x90, 0x18, 0x60, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_CONTROL_WHITE_0
#define LV_ATTRIBUTE_IMG_CONTROL_WHITE_0
#endif

// Autogenerated map from control_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_CONTROL_WHITE_0 uint8_t
    control_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
        /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
        0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
        /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
        0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

        /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
        0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x80, 0x00, 0xc0, 0x00, 0x60, 0x00, 0x30, 0x00,
        0x30, 0x00, 0x60, 0x00, 0xc0, 0x01, 0x80, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_OPT_WHITE_0
#define LV_ATTRIBUTE_IMG_OPT_WHITE_0
#endif

// Autogenerated map from opt_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_OPT_WHITE_0 uint8_t opt_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x00, 0x30, 0x00, 0x30, 0x01, 0xf0, 0x0f, 0xc0, 0x3e, 0x00,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_SHIFT_WHITE_0
#define LV_ATTRIBUTE_IMG_SHIFT_WHITE_0
#endif

// Autogenerated map from shift_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_SHIFT_WHITE_0 uint8_t shift_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x02, 0x00, 0x03, 0x00, 0x03, 0x80, 0x3e, 0xc0, 0x20, 0x60, 0x20, 0x30, 0x20, 0x30,
    0x20, 0x60, 0x3e, 0xc0, 0x03, 0x80, 0x03, 0x00, 0x02, 0x00, 0x00, 0x00};

#ifndef LV_ATTRIBUTE_IMG_WIN_WHITE_0
#define LV_ATTRIBUTE_IMG_WIN_WHITE_0
#endif

// Autogenerated map from win_white_0.png
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_WIN_WHITE_0 uint8_t win_white_0_map[] = {
#if CONFIG_NICE_OLED_WIDGET_INVERTED
    /*Palette: Idx 0: White (#else), Idx 1: Black (#else)*/
    0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#else
    /*Palette: Idx 0: Black (#if), Idx 1: White (#if)*/
    0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#endif

    /*Pixel data (1 bit per pixel, 0=palette idx 0, 1=palette idx 1)*/
    0x00, 0x00, 0x00, 0x00, 0x1d, 0xc0, 0x1d, 0xc0, 0x1d, 0xe0, 0x00, 0x00, 0x3d, 0xe0, 0x3d, 0xe0,
    0x3d, 0xf0, 0x3d, 0xf0, 0x7d, 0xf0, 0x7d, 0xf0, 0x00, 0x00, 0x00, 0x00};

// Autogenerated descriptor for alt_0.png
const lv_img_dsc_t alt_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = alt_0_map,
};

// Autogenerated descriptor for cmd_0.png
const lv_img_dsc_t cmd_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = cmd_0_map,
};

// Autogenerated descriptor for control_0.png
const lv_img_dsc_t control_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = control_0_map,
};

// Autogenerated descriptor for opt_0.png
const lv_img_dsc_t opt_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = opt_0_map,
};

// Autogenerated descriptor for shift_0.png
const lv_img_dsc_t shift_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = shift_0_map,
};

// Autogenerated descriptor for win_0.png
const lv_img_dsc_t win_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = win_0_map,
};

// Autogenerated descriptor for alt_white_0.png
const lv_img_dsc_t alt_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = alt_white_0_map,
};

// Autogenerated descriptor for cmd_white_0.png
const lv_img_dsc_t cmd_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = cmd_white_0_map,
};

// Autogenerated descriptor for control_white_0.png
const lv_img_dsc_t control_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = control_white_0_map,
};

// Autogenerated descriptor for opt_white_0.png
const lv_img_dsc_t opt_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = opt_white_0_map,
};

// Autogenerated descriptor for shift_white_0.png
const lv_img_dsc_t shift_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = shift_white_0_map,
};

// Autogenerated descriptor for win_white_0.png
const lv_img_dsc_t win_white_0 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 14,
    .header.h = 14,
    .data_size = 36,
    .data = win_white_0_map,
};
